version: "3.9"

services:
  nodetwitch:
    image: node
    container_name: projectnode
    ports:
      - 5000:3000
    build: .
    command: node server.js
  db:
    image: mongo
    container_name: mymongotest
    ports:
      - 27017:27017
